# Generated by Django 5.0.4 on 2024-04-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_category_options_alter_material_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='author',
        ),
    ]
